default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: "www.sij.it"
  username: sunbet
  password: SiJatSA3

development:
  primary:
    <<: *default
    database: examino_deve

  secondary:
    <<: *default
    database: modsnai_prod
    username: snai
    replica: true

  tertiary_sunbet:
    <<: *default
    database: sunbet_net_development
    username: sunbet
    replica: true

  tertiary_nevada:
    <<: *default
    database: nevada_net_development
    username: sunbet
    replica: true

  tertiary_romar:
    <<: *default
    database: romar_net_development
    username: romar
    replica: true

  tertiary_totalbet:
    <<: *default
    database: totalbet_net_development
    username: totalbet
    replica: true

  cable:
    <<: *default
    database: examino_deve

  queue:
    <<: *default
    database: examino_deve

  cache:
    <<: *default
    database: examino_deve

production:
  primary:
    <<: *default
    database: examino_prod

  secondary:
    <<: *default
    database: modsnai_prod
    username: snai
    replica: true

  tertiary_sunbet:
    <<: *default
    database: sunbet_net_production
    username: sunbet
    replica: true

  tertiary_nevada:
    <<: *default
    database: nevada_net_production
    username: sunbet
    replica: true

  tertiary_romar:
    <<: *default
    database: romar_net_production
    username: romar
    replica: true

  tertiary_totalbet:
    <<: *default
    database: totalbet_net_production
    username: totalbet
    replica: true

  cable:
    <<: *default
    database: examino_prod

  queue:
    <<: *default
    database: examino_prod

  cache:
    <<: *default
    database: examino_prod